---
- name: create zabbix system user
  user:
    name: zabbix-docker
    comment: 'zabbix docker system user'
    system: true
    uid: 2450
  become: true
- name: pull mysql docker image
  docker_image:
    name: mysql
    tag: latest
  become: true
- name: pull zabbix nginx docker image
  docker_image:
    name: zabbix/zabbix-web-nginx-mysql
    tag: latest
  become: true
- name: pull zabbix server docker image
  docker_image:
    name: zabbix/zabbix-server-mysql
    tag: latest
  become: true
- name: create /opt/zabbix-docker directory
  file:
    path: /opt/zabbix-docker
    mode: 0700
    owner: 2450
    state: directory
  become: true
- name: create zabbix docker mysql directory
  file:
    path: /opt/zabbix-docker/mysql
    mode: 0700
    owner: 2450
    state: directory
  become: true
- name: create zabbix nginx directory
  file:
    path: /opt/zabbix-docker/nginx
    mode: 0700
    owner: 2450
    state: directory
  become: true
- name: create zabbix docker server directory
  file:
    path: /opt/zabbix-docker/server
    mode: 0700
    owner: 2450
    state: directory
  become: true
- name: run mysql docker container
  docker_container:
    name: zabbix_mysql
    image: mysql:latest
    state: started
    restart_policy: unless-stopped
    env:
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
    - /opt/zabbix-docker/mysql:/var/lib/mysql
  become: true
- name: run zabbix server docker container
  docker_container:
    name: zabbix
    image: zabbix/zabbix-server-mysql
    state: started
    restart_policy: unless-stopped
    ports:
    - 10051:10051
    links:
    - zabbix_mysql:mysql
    env:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    volumes:
    - /opt/zabbix-docker/server:/var/lib/zabbix/
  become: true
- name: run zabbix nginx docker container
  docker_container:
    name: zabbix_nginx
    image: zabbix/zabbix-web-nginx-mysql
    state: started
    restart_policy: unless-stopped
    links:
    - zabbix
    - zabbix_mysql:mysql
    env:
      ZBX_SERVER_HOST: "{{ nginx_host }}" 
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    ports:
    - "{{ nginx_http_port }}:80"
  become: true
