---
- name: create zabbix system user
  user:
    name: zabbix-docker
    comment: 'zabbix docker system user'
    system: true
    uid: 2450
  become: true
- name: pull mysql docker image
  docker_image:
    name: mysql
    tag: latest
  become: true
- name: pull nginx docker image
  docker_image:
    name: nginx
    tag: latest
  become: true
- name: pull zabbix java gateway docker image
  docker_image:
    name: zabbix/zabbix-java-gateway
    tag: latest
  become: true
- name: pull zabbix server docker image
  docker_image:
    name: zabbix/zabbix-server-mysql
    tag: latest
  become: true
- name: create /opt/zabbix-docker directory
  file:
    path: /opt/zabbix-docker
    mode: 0700
    owner: 2450
    state: directory
  become: true
- name: create zabbix docker mysql directory
  file:
    path: /opt/zabbix-docker/mysql
    mode: 0700
    owner: 2450
    state: directory
  become: true
- name: create zabbix nginx directory
  file:
    path: /opt/zabbix-docker/nginx
    mode: 0700
    owner: 2450
    state: directory
  become: true
- name: create zabbix docker server directory
  file:
    path: /opt/zabbix-docker/server
    mode: 0700
    owner: 2450
    state: directory
  become: true
- name: run mysql docker container
  docker_container:
    name: zabbix_mysql
    image: mysql:latest
    state: started
    restart_policy: unless-stopped
    user: 2450
    env:
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
    - /opt/zabbix-docker/mysql:/var/lib/mysql
  become: true
- name: run zabbix java gateway docker container
  docker_container:
    name: zabbix_java_gateway
    image: zabbix/zabbix-java-gateway:latest
    state: started
    restart_policy: unless-stopped
    user: 2450
  become: true
- name: generate ssl key
  shell: openssl genrsa -out /opt/zabbix-docker/nginx/server.key 4096
  become: true
- name: generate csr
  shell: openssl req -new -key /opt/zabbix-docker/nginx/server.key -out /opt/zabbix-docker/nginx/server.csr -subj "{{ self_sign_ssl_options }}"
  become: true
- name: generate cert
  shell: openssl x509 -req -days 366 -in /opt/zabbix-docker/nginx/server.csr -signkey /opt/zabbix-docker/nginx/server.key -out /opt/zabbix-docker/nginx/server.cert
  become: true
- name: change ownership of /opt/zabbix-docker/nginx files to zabbix-docker
  file:
    path: /opt/zabbix-docker/nginx/server.csr
    owner: 2450
    mode: 0600
  become: true
- name: change ownership of /opt/zabbix-docker/nginx files to zabbix-docker
  file:
    path: /opt/zabbix-docker/nginx/server.key
    owner: 2450
    mode: 0600
  become: true
- name: change ownership of /opt/zabbix-docker/nginx files to zabbix-docker
  file:
    path: /opt/zabbix-docker/nginx/server.cert
    owner: 2450
    mode: 0600
  become: true
- name: run zabbix server docker container
  docker_container:
    name: zabbix
    image: zabbix/zabbix-server-mysql
    state: started
    restart_policy: unless-stopped
    links:
    - zabbix_mysql:mysql
    - zabbix_java_gateway:zabbix_java_gateway
    env:
      ZBX_JAVAGATEWAY: zabbix_java_gateway"
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    volumes:
    - /opt/zabbix-docker/server:/var/lib/zabbix/
  become: true
- name: copy nginx config to /opt/zabbix-docker/nginx/nginx.conf
  copy:
    src: nginx.conf
    dest: /opt/zabbix-docker/nginx/nginx.conf
    owner: 2450
    mode: 0600
  become: true
- name: run zabbix nginx docker container
  docker_container:
    name: zabbix_nginx
    image: nginx
    state: started
    restart_policy: unless-stopped
    links:
    - zabbix
    env:
      DB_SERVER_HOST: mysql
    ports:
    - "{{ nginx_https_port }}:{{ nginx_https_port }}"
    volumes:
    - /opt/zabbix-docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - /opt/zabbix-docker/nginx/server.cert:/tmp/server.cert 
    - /opt/zabbix-docker/nginx/server.key:/tmp/server.key 
  become: true
